webtalk_init -webtalk_dir C:/Users/Joseph/Desktop/Current HW/FPGA HW/Vivado Projects/A5_problem2/A5_problem2.sim/sim_2/behav/xsim/xsim.dir/master_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 28 11:14:36 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea588496-be57-45bc-938a-bca39419f72b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "22b349cde3cb4669bba94415993d215c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2012 R2 or Windows 8.1" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "365 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 640405930 -regid "" -xml C:/Users/Joseph/Desktop/Current HW/FPGA HW/Vivado Projects/A5_problem2/A5_problem2.sim/sim_2/behav/xsim/xsim.dir/master_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Joseph/Desktop/Current HW/FPGA HW/Vivado Projects/A5_problem2/A5_problem2.sim/sim_2/behav/xsim/xsim.dir/master_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Joseph/Desktop/Current HW/FPGA HW/Vivado Projects/A5_problem2/A5_problem2.sim/sim_2/behav/xsim/xsim.dir/master_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
